// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/otp.proto

package otp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Generate an OTP (one time pass) code
type GenerateRequest struct {
	// unique id, email or user to generate an OTP for
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// number of characters (default: 6)
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// expiration in seconds (default: 60)
	Expiry               int64    `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61458fd439c452e, []int{0}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenerateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GenerateRequest) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type GenerateResponse struct {
	// one time pass code
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61458fd439c452e, []int{1}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// Validate the OTP code
type ValidateRequest struct {
	// unique id, email or user for which the code was generated
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// one time pass code to validate
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61458fd439c452e, []int{2}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ValidateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ValidateResponse struct {
	// returns true if the code is valid for the ID
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61458fd439c452e, []int{3}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "otp.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "otp.GenerateResponse")
	proto.RegisterType((*ValidateRequest)(nil), "otp.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "otp.ValidateResponse")
}

func init() {
	proto.RegisterFile("proto/otp.proto", fileDescriptor_b61458fd439c452e)
}

var fileDescriptor_b61458fd439c452e = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x29, 0xd0, 0x03, 0xb3, 0x84, 0x98, 0xf3, 0x4b, 0x0a, 0x94, 0x7c, 0xb9,
	0xf8, 0xdd, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53,
	0x84, 0x84, 0xb8, 0x58, 0x8a, 0x33, 0xab, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0xc0,
	0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xd4, 0x8a, 0x82, 0xcc, 0xa2, 0x4a, 0x09, 0x66, 0xb0, 0x28, 0x94,
	0xa7, 0xa4, 0xc6, 0x25, 0x80, 0x30, 0xae, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0xa4, 0x3f, 0x39,
	0x3f, 0x25, 0x15, 0x6a, 0x22, 0x98, 0xad, 0x64, 0xca, 0xc5, 0x1f, 0x96, 0x98, 0x93, 0x99, 0x82,
	0xdf, 0x5a, 0xb0, 0x36, 0x26, 0x24, 0x6d, 0x3a, 0x5c, 0x02, 0x08, 0x6d, 0x50, 0xe3, 0x25, 0xb8,
	0xd8, 0x8b, 0x4b, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xc1, 0x9a, 0x39, 0x82, 0x60, 0x5c, 0xa3, 0x6a,
	0x2e, 0x66, 0xff, 0x92, 0x02, 0x21, 0x4b, 0x2e, 0x0e, 0x98, 0x9b, 0x84, 0x44, 0xf4, 0x40, 0xfe,
	0x47, 0xf3, 0xb1, 0x94, 0x28, 0x9a, 0x28, 0xc4, 0x64, 0x25, 0x06, 0x90, 0x56, 0x98, 0x7d, 0x50,
	0xad, 0x68, 0xae, 0x86, 0x6a, 0x45, 0x77, 0x94, 0x12, 0x83, 0x13, 0x6f, 0x14, 0xb7, 0x9e, 0x3e,
	0x38, 0xa0, 0xad, 0xf3, 0x4b, 0x0a, 0x92, 0xd8, 0xc0, 0x4c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x13, 0x0e, 0x2b, 0xe0, 0x86, 0x01, 0x00, 0x00,
}
